version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "io.coil-kt:coil"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
